#!/bin/bash
#SBATCH --job-name=base_rescore
#SBATCH --gres=gpu:1
#SBATCH --output=logs/output_%j.txt
#SBATCH --error=logs/error_%j.txt

# rescore the no-rag and naive-rag baselines on the v7-mix draw

mkdir -p logs
mkdir -p outputs
mkdir -p data/thesis_norag_v7mix
mkdir -p data/thesis_naiverag_v7mix

python scripts/build_baseline_data.py --mode norag --src data/thesis_rl_v7_control/test.parquet --out data/thesis_norag_v7mix/test.parquet

python scripts/build_baseline_data.py --mode naiverag --src data/thesis_rl_v7_control/test.parquet --out data/thesis_naiverag_v7mix/test.parquet --nprobe 512

python -m verl.trainer.main_ppo data.train_files=data/thesis_rl/train.parquet data.val_files=data/thesis_norag_v7mix/test.parquet data.train_batch_size=512 data.val_batch_size=64 data.val_data_num=256 data.max_prompt_length=4096 data.max_response_length=256 data.max_start_length=2048 data.max_obs_length=500 data.shuffle_train_dataloader=True algorithm.adv_estimator=grpo algorithm.no_think_rl=false actor_rollout_ref.model.path=models/qwen2.5-3b-it +actor_rollout_ref.model.inference_bf16=true actor_rollout_ref.model.enable_gradient_checkpointing=true actor_rollout_ref.model.use_remove_padding=True actor_rollout_ref.actor.optim.lr=1e-6 actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 actor_rollout_ref.actor.use_kl_loss=true actor_rollout_ref.actor.kl_loss_coef=0.001 actor_rollout_ref.actor.kl_loss_type=low_var_kl actor_rollout_ref.actor.ppo_mini_batch_size=256 actor_rollout_ref.actor.ppo_micro_batch_size=1 actor_rollout_ref.actor.state_masking=true actor_rollout_ref.actor.fsdp_config.param_offload=true actor_rollout_ref.actor.fsdp_config.grad_offload=true actor_rollout_ref.actor.fsdp_config.optimizer_offload=true +actor_rollout_ref.actor.fsdp_config.model_dtype=bf16 actor_rollout_ref.rollout.name=vllm actor_rollout_ref.rollout.temperature=1 actor_rollout_ref.rollout.n_agent=5 actor_rollout_ref.rollout.tensor_model_parallel_size=1 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 actor_rollout_ref.rollout.log_prob_micro_batch_size=1 actor_rollout_ref.ref.log_prob_micro_batch_size=1 actor_rollout_ref.ref.fsdp_config.param_offload=True retriever.url=local retriever.faiss_gpu=False retriever.topk=3 retriever.index_path=retrieval_data/e5_IVF.index retriever.corpus_path=retrieval_data/wiki-18.jsonl retriever.model_path=intfloat/e5-base-v2 budget_planner.enabled=false cost_reward.enabled=false max_turns=0 trainer.logger=['console','wandb'] +trainer.val_only=true +trainer.val_before_train=true trainer.default_hdfs_dir=null trainer.n_gpus_per_node=1 trainer.nnodes=1 trainer.save_freq=100 trainer.test_freq=50 trainer.project_name=FYP trainer.experiment_name=baseline_norag_v7mix trainer.total_epochs=15 trainer.total_training_steps=1005 trainer.default_local_dir=verl_checkpoints/baseline_norag_v7mix

python -m verl.trainer.main_ppo data.train_files=data/thesis_rl/train.parquet data.val_files=data/thesis_naiverag_v7mix/test.parquet data.train_batch_size=512 data.val_batch_size=64 data.val_data_num=256 data.max_prompt_length=4096 data.max_response_length=256 data.max_start_length=2048 data.max_obs_length=500 data.shuffle_train_dataloader=True algorithm.adv_estimator=grpo algorithm.no_think_rl=false actor_rollout_ref.model.path=models/qwen2.5-3b-it +actor_rollout_ref.model.inference_bf16=true actor_rollout_ref.model.enable_gradient_checkpointing=true actor_rollout_ref.model.use_remove_padding=True actor_rollout_ref.actor.optim.lr=1e-6 actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 actor_rollout_ref.actor.use_kl_loss=true actor_rollout_ref.actor.kl_loss_coef=0.001 actor_rollout_ref.actor.kl_loss_type=low_var_kl actor_rollout_ref.actor.ppo_mini_batch_size=256 actor_rollout_ref.actor.ppo_micro_batch_size=1 actor_rollout_ref.actor.state_masking=true actor_rollout_ref.actor.fsdp_config.param_offload=true actor_rollout_ref.actor.fsdp_config.grad_offload=true actor_rollout_ref.actor.fsdp_config.optimizer_offload=true +actor_rollout_ref.actor.fsdp_config.model_dtype=bf16 actor_rollout_ref.rollout.name=vllm actor_rollout_ref.rollout.temperature=1 actor_rollout_ref.rollout.n_agent=5 actor_rollout_ref.rollout.tensor_model_parallel_size=1 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 actor_rollout_ref.rollout.log_prob_micro_batch_size=1 actor_rollout_ref.ref.log_prob_micro_batch_size=1 actor_rollout_ref.ref.fsdp_config.param_offload=True retriever.url=local retriever.faiss_gpu=False retriever.topk=3 retriever.index_path=retrieval_data/e5_IVF.index retriever.corpus_path=retrieval_data/wiki-18.jsonl retriever.model_path=intfloat/e5-base-v2 budget_planner.enabled=false cost_reward.enabled=false max_turns=0 trainer.logger=['console','wandb'] +trainer.val_only=true +trainer.val_before_train=true trainer.default_hdfs_dir=null trainer.n_gpus_per_node=1 trainer.nnodes=1 trainer.save_freq=100 trainer.test_freq=50 trainer.project_name=FYP trainer.experiment_name=baseline_naiverag_v7mix trainer.total_epochs=15 trainer.total_training_steps=1005 trainer.default_local_dir=verl_checkpoints/baseline_naiverag_v7mix
